swagger: '2.0'
info:
  version: 0.1.0
  title: WMF MobileApps service
  description: A prototype for MediaWiki REST API services for mobile apps
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Reading team
    url: http://mediawiki.org/wiki/Reading
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
x-default-params:
  domain: en.wikipedia.org
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  # from routes/featured.js
  /{domain}/v1/page/featured/{yyyy}/{mm}/{dd}:
    get:
      tags:
        - Featured article for a given date
      description: title of the featured article (only works on enwiki for now)
      produces:
        - application/json
      parameters:
        - name: yyyy
          in: path
          description: "Year the featured article is requested for"
          type: string
          required: true
          minimum: "2016"
          maximum: "2999"
        - name: mm
          in: path
          description: "Month the featured article is requested for"
          type: string
          required: true
          minimum: "01"
          maximum: "12"
        - name: dd
          in: path
          description: "Day of the month the featured article is requested for"
          type: string
          required: true
          minimum: "01"
          maximum: "31"
      x-amples:
        - title: retrieve title of the featured article for April 29, 2016
          request:
            params:
              yyyy: "2016"
              mm: "04"
              dd: "29"
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              title: /.+/
              description: /.+/
              extract: /.+/
              thumbnail:
                source: /.+/
                width: /.+/
                height: /.+/
        - title: retrieve featured article info for unsupported site (with aggregated=true)
          request:
            params:
              domain: "is.wikipedia.org"
              yyyy: "2016"
              mm: "04"
              dd: "29"
            query:
              aggregated: true
          response:
            status: 200
            body: ""
  # from routes/featured-image.js
  /{domain}/v1/media/image/featured/{yyyy}/{mm}/{dd}:
    get:
      tags:
        - Featured image for a given date (aka Picture of the day)
      description: Provides thumbnail and full res image URLs and a localized description based on the domain used.
      produces:
        - application/json
      parameters:
        - name: yyyy
          in: path
          description: "Year the featured image is requested for"
          type: string
          required: true
          minimum: "2016"
          maximum: "2999"
        - name: mm
          in: path
          description: "Month the featured image is requested for"
          type: string
          required: true
          minimum: "01"
          maximum: "12"
        - name: dd
          in: path
          description: "Day of the month the featured image is requested for"
          type: string
          required: true
          minimum: "01"
          maximum: "31"
      x-amples:
        - title: retrieve featured image data for April 29, 2016
          request:
            params:
              yyyy: "2016"
              mm: "04"
              dd: "29"
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              title: /.+/
              description:
                text: /.+/
                lang: /.+/
              image:
                source: /.+/
                width: /.+/
                height: /.+/
              thumbnail:
                source: /.+/
                width: /.+/
                height: /.+/
        - title: retrieve featured image data for date with no featured image (with aggregated=true)
          request:
            params:
              yyyy: "2004"
              mm: "04"
              dd: "29"
            query:
              aggregated: true
          response:
            status: 200
            body: ""
  # from routes/most-read.js
  /{domain}/v1/page/most-read/{yyyy}/{mm}/{dd}:
    get:
      tags:
        - Most-read articles
      description: Gets the most-read articles for the date provided
      produces:
        - application/json
      parameters:
        - name: yyyy
          in: path
          description: "Year the most-read articles are requested for"
          type: string
          required: true
          minimum: "2016"
          maximum: "2999"
        - name: mm
          in: path
          description: "Month the most-read articles are requested for"
          type: string
          required: true
          minimum: "01"
          maximum: "12"
        - name: dd
          in: path
          description: "Day of the month the most-read articles are requested for"
          type: string
          required: true
          minimum: "01"
          maximum: "31"
      x-amples:
        - title: retrieve the most-read articles for January 1, 2016
          request:
            params:
              yyyy: "2016"
              mm: "01"
              dd: "01"
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              date: "2016-01-01Z"
              articles:
                - views: /.+/
                  rank: /.+/
                  title: /.+/
        - title: retrieve the most-read articles for January 1, 2016 (with aggregated=true)
          request:
            params:
              yyyy: "2016"
              mm: "01"
              dd: "01"
            query:
              aggregated: true
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              date: "2015-12-31Z"
              articles:
                - views: /.+/
                  rank: /.+/
                  title: /.+/
        - title: retrieve most-read articles for date with no data (with aggregated=true)
          request:
            params:
              yyyy: "2015"
              mm: "01"
              dd: "01"
            query:
              aggregated: true
          response:
            status: 200
            body: ""
  # from routes/random.js
  /{domain}/v1/page/random/title:
    get:
      tags:
        - Random article title
      description: Gets the title of a randomly picked article from main namespace. Preference is given to articles with a thumbnail, long extract, and an associated Wikidata description.
      produces:
        - application/json
      x-amples:
        - title: retrieve a random article
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - title: /.+/
  # from routes/news.js
  /{domain}/v1/page/news:
    get:
      tags:
        - News-related content
      description: Gets content related to the current In the News template (experimental, English-only).
      produces:
        - application/json
      x-amples:
        - title: get 'In the News' content
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              - story: /.+/
                links:
                  - title: /.+/
        - title: get 'In the News' content for unsupported language (with aggregated=true)
          request:
            params:
              domain: "is.wikipedia.org"
            query:
              aggregated: true
          response:
            status: 200
            body: ""
  # from routes/media.js
  /{domain}/v1/page/media/{title}:
    get:
      tags:
        - Media items on a given page
      description: Gets the images and videos which appear on a given wiki page
      produces:
        - application/json
      x-amples:
        - title: retrieve images and videos of en.wp Cat page via media route
          request:
            params:
              title: Cat
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - title: /.+/
                  url: /.+/
                  width: /.+/
                  height: /.+/
  # from routes/definition.js
  /{domain}/v1/page/definition/{title}:
    get:
      tags:
        - Wiktionary definition of {title}
      description: Gets definitions parsed from Wiktionary for {title}
      produces:
        - application/json
      x-amples:
        - title: retrieve en-wiktionary definitions for 'cat'
          request:
            params:
              domain: en.wiktionary.org
              title: cat
          response:
            status: 200
            headers:
              content-type: application/json
            body: /.+/
  # from routes/mobile-sections.js
  /{domain}/v1/page/mobile-sections/{title}:
    get:
      tags:
        - Page content
      description: Gets the full page content of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve en.wp main page via mobile-sections
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              lead:
                id: /.+/
                revision: /.+/
                lastmodified: /.+/
                lastmodifier: /.+/
                displaytitle: /.+/
                normalizedtitle: /.+/
                description: /[Mm]ain [Pp]age/
                protection: /.+/
                editable: /.+/
                mainpage: true
                languagecount: /.+/
                ns: /.+/
                sections: [ /.+/ ]
              remaining:
                sections: []
  /{domain}/v1/page/mobile-sections-lead/{title}:
    get:
      tags:
        - Lead section of page content
      description: Gets the lead section and general metadata of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve lead section of en.wp Altrincham page via mobile-sections-lead
          request:
            params:
              title: Altrincham
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              lastmodifier: /.+/
              displaytitle: /.+/
              description: /.+/
              protection: /.+/
              editable: /.+/
              languagecount: /.+/
              ns: /.+/
              pronunciation:
                url: /.+/
              spoken:
                files: [ /.+/ ]
              geo:
                latitude: /.+/
                longitude: /.+/
              sections: [ /.+/ ]
  /{domain}/v1/page/mobile-sections-remaining/{title}:
    get:
      tags:
        - Lead section of page content
      description: Gets the remaining sections of a given wiki page for mobile apps
      produces:
        - application/json
      x-monitor: false
  # from routes/mobile-summary.js
  /{domain}/v1/page/mobile-summary/{title}:
    get:
      tags:
        - Link preview data of page
      description: Gets a summary of the page so the user can evaluate if to open the page
      produces:
        - application/json
      x-amples:
        - title: retrieve page preview of Dog page
          request:
            params:
              title: Dog
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              title: Dog
              extract: /.+/
              thumbnail:
                source: /.+/
              infobox: [ /.+/ ]
  # from routes/mobile-text.js
  /{domain}/v1/page/mobile-text/{title}:
    get:
      tags:
        - Page content
      description: Gets the lite mobile app version of a given wiki page
      produces:
        - application/json
      x-monitor: false
