swagger: '2.0'
info:
  version: 0.0.3
  title: WMF MobileApps service
  description: A prototype for MediaWiki REST API services for mobile apps
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Reading team
    url: http://mediawiki.org/wiki/Reading
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
x-default-params:
  domain: en.wikipedia.org
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  # from routes/mobile-html.js
  /{domain}/v1/page/mobile-html/{title}:
    get:
      tags:
        - Page content
      description: Gets the mobile app version of a given wiki page (all HTML payload, on hold)
      produces:
        - text/html
      x-amples:
        - title: retrieve en.wp main page via mobile-html
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: text/html
            body: /.+/
  # from routes/mobile-html-sections.js
  /{domain}/v1/page/mobile-html-sections/{title}:
    get:
      tags:
        - Page content
      description: Gets the full page content of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve en.wp main page via mobile-html-sections
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              lead:
                id: /.+/
                revision: /.+/
                lastmodified: /.+/
                displaytitle: /.+/
                protection: /.+/
                editable: /.+/
                languagecount: /.+/
                media:
                  items: [ /.+/ ]
                sections: [ /.+/ ]
              remaining:
                sections: []
  /{domain}/v1/page/mobile-html-sections-lead/{title}:
    get:
      tags:
        - Lead section of page content
      description: Gets the lead section and general metadata of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve lead section of en.wp main page via mobile-html-sections-lead
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              displaytitle: /.+/
              protection: /.+/
              editable: /.+/
              languagecount: /.+/
              media:
                items: [ /.+/ ]
              sections: [ /.+/ ]
        - title: retrieve lead section of en.wp San Francisco page via mobile-html-sections-lead
          request:
            params:
              title: San_Francisco
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              displaytitle: /.+/
              protection: /.+/
              editable: /.+/
              languagecount: /.+/
              extract: /.+/
              media:
                items: [ /.+/ ]
              infobox: [ [ /.+/ ] ]
              geo:
                latitude: /.+/
                longitude: /.+/
              sections: [ /.+/ ]
        - title: retrieve lead section of en.wp Barack Obama page via mobile-html-sections-lead
          request:
            params:
              title: Barack_Obama
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              displaytitle: /.+/
              protection: /.+/
              editable: /.+/
              languagecount: /.+/
              media:
                items: [ /.+/ ]
              infobox: [ [ /.+/ ] ]
              pronunciation:
                url: /.+/
              sections: [ /.+/ ]
  /{domain}/v1/page/mobile-html-sections-remaining/{title}:
    get:
      tags:
        - Lead section of page content
      description: Gets the remaining sections of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve remaining sections of en.wp main page via mobile-html-sections-remaining
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              sections: []
  # from routes/mobile-text.js
  /{domain}/v1/page/mobile-text/{title}:
    get:
      tags:
        - Page content
      description: Gets the lite mobile app version of a given wiki page
      produces:
        - application/json
      x-amples:
        - title: retrieve the lite en.wp main page
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body: /.+/
