swagger: '2.0'
info:
  version: 0.1.0
  title: WMF MobileApps service
  description: A prototype for MediaWiki REST API services for mobile apps
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Reading team
    url: http://mediawiki.org/wiki/Reading
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
x-default-params:
  domain: en.wikipedia.org
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  # from routes/media.js
  /{domain}/v1/page/media/{title}:
    get:
      tags:
        - Media items on a given page
      description: Gets the images and videos which appear on a given wiki page
      produces:
        - application/json
      x-amples:
        - title: retrieve images and videos of en.wp Cat page via media route
          request:
            params:
              title: Cat
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - title: /.+/
                  url: /.+/
                  width: /.+/
                  height: /.+/
  # from routes/definition.js
  /{domain}/v1/page/definition/{title}:
    get:
      tags:
        - Wiktionary definition of {title}
      description: Gets definitions parsed from Wiktionary for {title}
      produces:
        - application/json
      x-amples:
        - title: retrieve en-wiktionary definitions for 'cat'
          request:
            params:
              domain: en.wiktionary.org
              title: cat
          response:
            status: 200
            headers:
              content-type: application/json
            body: /.+/
  # from routes/mobile-sections.js
  /{domain}/v1/page/mobile-sections/{title}:
    get:
      tags:
        - Page content
      description: Gets the full page content of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve en.wp main page via mobile-sections
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              lead:
                id: /.+/
                revision: /.+/
                lastmodified: /.+/
                displaytitle: /.+/
                normalizedtitle: /.+/
                description: main page of a Wikimedia project
                protection: /.+/
                editable: /.+/
                mainpage: true
                languagecount: /.+/
                sections: [ /.+/ ]
              remaining:
                sections: []
  /{domain}/v1/page/mobile-sections-lead/{title}:
    get:
      tags:
        - Lead section of page content
      description: Gets the lead section and general metadata of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve lead section of en.wp main page via mobile-sections-lead
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              displaytitle: /.+/
              normalizedtitle: /.+/
              description: main page of a Wikimedia project
              protection: /.+/
              editable: /.+/
              mainpage: true
              languagecount: /.+/
              sections: [ /.+/ ]
        - title: retrieve lead section of en.wp San Francisco page via mobile-sections-lead
          request:
            params:
              title: San_Francisco
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              displaytitle: /.+/
              normalizedtitle: /.+/
              description: /.+/
              protection: /.+/
              editable: /.+/
              languagecount: /.+/
              geo:
                latitude: /.+/
                longitude: /.+/
              sections: [ /.+/ ]
        - title: retrieve lead section of en.wp Barack Obama page via mobile-sections-lead
          request:
            params:
              title: Barack_Obama
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              id: /.+/
              revision: /.+/
              lastmodified: /.+/
              displaytitle: /.+/
              normalizedtitle: /.+/
              description: /.+/
              protection: /.+/
              editable: /.+/
              languagecount: /.+/
              pronunciation:
                url: /.+/
              spoken:
                files: [ /.+/ ]
              sections: [ /.+/ ]
  /{domain}/v1/page/mobile-sections-remaining/{title}:
    get:
      tags:
        - Lead section of page content
      description: Gets the remaining sections of a given wiki page for mobile apps
      produces:
        - application/json
      x-amples:
        - title: retrieve remaining sections of en.wp main page via mobile-sections-remaining
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              sections: []
  # from routes/mobile-summary.js
  /{domain}/v1/page/mobile-summary/{title}:
    get:
      tags:
        - Link preview data of page
      description: Gets a summary of the page so the user can evaluate if to open the page
      produces:
        - application/json
      x-amples:
        - title: retrieve page preview of Dog page
          request:
            params:
              title: Dog
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              title: Dog
              extract: /.+/
              thumbnail:
                source: /.+/
              infobox: [ /.+/ ]
  # from routes/mobile-text.js
  /{domain}/v1/page/mobile-text/{title}:
    get:
      tags:
        - Page content
      description: Gets the lite mobile app version of a given wiki page
      produces:
        - application/json
      x-amples:
        - title: retrieve the lite en.wp main page
          request:
            params:
              title: Main_Page
          response:
            status: 200
            headers:
              content-type: application/json
            body: /.+/
